name: Build Sphinx Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
    
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Add Sphinx to the requirements if not already there
          pip install -r requirements.txt
          pip install sphinx

      - name: Build HTML
        run: |
          cd src/docs/
          make html

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to GitHub Pages
        run: |
          pip install ghp-import
          ghp-import -n -p -f src/docs/_build/html
