name: Build-sphinx-docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
    

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
    
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel
          pip install -r requirements.txt

      - name: Build HTML
        run: |
          cd src/docs/
          make html

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to gh-pages
        run: |
          pip install ghp-import
          ghp-import -n -p -f src/docs/_build/html